GET http://localhost:3000

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "nurul",
    "password": "12345678"
}

###

POST http://localhost:3000/register
Content-Type: application/json 
//header : what is the content type

{
    "username": "nurul",
    "password": "12345678",
    "name": "farahhh",
    "email": "farah067@gmail.com"
}